# zshrc

# add wrappers to path
PATH="$PATH:$DISTROBOX_DIR/wrappers"

# change history file
HISTFILE="$HOME/.cache/zhistory_${HOST%.*}"

# default editor
EDITOR=nvim

# devbox
if command -v devbox >/dev/null; then
    eval "$(devbox global shellenv --recompute)"
fi
